name = "costco-deals-finder-dev"
main = "src/worker.ts"
compatibility_date = "2024-02-20"

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "costco-dev"
database_id = "fabd27a5-44c6-47cb-b3b5-6d8c83863363" 